#!/bin/bash
set -eo pipefail

if [[ -z "${GH_TOKEN}" ]]; then
  echo "The GH_TOKEN environment variable is not set" >&2
  exit 1
fi

name='configlet.tar.gz'
gh -R exercism/configlet release download --output "${name}" \
  --pattern 'configlet-linux-64bit.tgz'
tar xzf "${name}" -C bin/
rm "${name}"
